[build-system]
requires = [
  "setuptools>=61",
  "wheel",
  "build",
  "numpy>=1.26",
  "cmake>=3.22",
  "ninja",
]
build-backend = "setuptools.build_meta"

[project]
name = "asnumpy" 
dynamic = ["version"]
description = "A NumPy-like library accelerated by Ascend NPU"
readme = "README.md"
authors = [{ name = "神里绫华的狗", email = "wuzhenqing@stu.hit.edu.cn" }]
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux"
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.26.0"
]

[tool.setuptools]
packages = ["asnumpy", "asnumpy.lib"]

[tool.setuptools.dynamic]
version = { attr = "asnumpy.__version__" }